# Generated by Django 5.2 on 2025-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_airqualitydata_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestationdata',
            old_name='reforestation_area',
            new_name='relative_deforestation_rate',
        ),
        migrations.RemoveField(
            model_name='deforestationdata',
            name='forest_area',
        ),
        migrations.RemoveField(
            model_name='deforestationdata',
            name='region',
        ),
    ]
